name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          MERGE_LABELS: "automerge, !work in progress, !wip"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_COMMIT_MESSAGE_REGEX: (.*)^---
          MERGE_DELETE_BRANCH: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"